config/routes.rb
Project::Application.routes.draw do
  resources :contacts

  resources :promotions

  resources :references

  resources :products

  resources :services

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :posts

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :service
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :service
end

app/models/reference.rb
class Reference < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :products
  has_many :promotions

  has_attached_file :image, :path => ":rails_root/app/assets/images/services/:id/:style/:filename",
                            :url => "/assets/images/:id/:basename.:extension"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout "activo"
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
end

app/controllers/promotions_controller.rb
class PromotionsController < InheritedResources::Base
end

app/controllers/references_controller.rb
class ReferencesController < InheritedResources::Base
end

app/controllers/services_controller.rb
class ServicesController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.address %></td>
    <td><%= contact.phone %></td>
    <td><%= contact.description %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Address:</b>
  <%= @contact.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @contact.phone %>
</p>

<p>
  <b>Description:</b>
  <%= @contact.description %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/activo.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><%= @title || "Untitled Page" %></title>
  
  <%= stylesheet_link_tag "jquery-ui.css", :media => "screen" %>
  <%= stylesheet_link_tag "base.css", :media => "screen" %>
  <%= stylesheet_link_tag "jquery.tipsy.css", :media => "screen" %>
  <%= stylesheet_link_tag "activo/activo.css", :media => "screen", :id => "current-theme" %>
  <!--[if IE]>
    <%= stylesheet_link_tag "activo/activo-ie.css", :media => "screen" %>
  <![endif]-->
  <%= stylesheet_link_tag "activo-attrtastic/attrtastic_changes.css", :media => "screen" %>
  <%= stylesheet_link_tag "activo-formtastic/formtastic.css", :media => "screen" %>
  <%= stylesheet_link_tag "activo-formtastic/formtastic_changes.css", :media => "screen" %>
  <%= stylesheet_link_tag "application.css", :media => "screen" %>
  
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js" %>
  <%= javascript_include_tag "jquery.scrollTo.js" %>
  <%= javascript_include_tag "jquery.localscroll.js" %>
  <%= javascript_include_tag "application.js" %>
  <%= javascript_include_tag "jquery.tipsy.js" %>
  <%= javascript_include_tag "rails.js" %>
  
  <%= csrf_meta_tag %>
  
  <%= head if respond_to? :head %>
  <%= yield :head %>
</head>

<body>
  <div id="container">
    <div id="header">
      <%= content_tag("div", status_menu, :id => "status") if respond_to? :status_menu %>
      <h1><a href="index.html"></a></h1>
      <%= navigation(:id => "user-navigation") { |n| user_navigation(n) } if respond_to?(:user_navigation) %>
      <%= navigation(:id => "main-navigation") { |n| main_navigation(n) } if respond_to?(:main_navigation) %>
    </div>
    <div id="wrapper" class="wat-cf">
      <div id="<%= @full_width ? 'full-main' : 'main' %>">
        <div class="flash">
          <% [ :warning, :notice, :error ].each do |f| -%>
            <%= content_tag("div", "<p>#{flash[f]}</p>".html_safe, :class => "message #{f}") unless flash[f].nil? %>
          <% end %>
        </div>
        <%= yield %>
      </div>
      <% if respond_to? :sidebar %>
        <div id="sidebar">
          <%= sidebar %>
        </div>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag "common"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<nav>
  <ul>
    <li><a href='/carrots'>Carrots</a></li>
    <li><a href='/pineapples'>Pineapples</a></li>
    <li><a href='/ginger'>Ginger</a></li>
  </ul>
</nav>
<div class="block">
  <%= secondary_navigation do |n|
    n.item "The Company","#", :active => true
    n.item "Our Offices","#"
    n.item "Jobs","#", :class => "highlighted"
  end %>
  <div class="content">
    <h2>About Us</h2>
    <div class="inner">
      <p>We're an amazing company! We do things!</p>
      <p>To find out more, click the tabs above.</p>
    </div>
  </div>
</div>
<%=image_tag("bnt_edit.png")%>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Text:</b>
  <%= @post.text %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :use %><br />
    <%= f.text_area :use %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Place</th>
    <th>Use</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.place %></td>
    <td><%= product.use %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Place:</b>
  <%= @product.place %>
</p>

<p>
  <b>Use:</b>
  <%= @product.use %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/promotions/_form.html.erb
<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% @promotion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :discout %><br />
    <%= f.number_field :discout %>
  </div>
  <div class="field">
    <%= f.label :service_id %><br />
    <%= f.number_field :service_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editing promotion</h1>

<%= render 'form' %>

<%= link_to 'Show', @promotion %> |
<%= link_to 'Back', promotions_path %>

app/views/promotions/index.html.erb
<h1>Listing promotions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Discout</th>
    <th>Service</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promotions.each do |promotion| %>
  <tr>
    <td><%= promotion.name %></td>
    <td><%= promotion.discout %></td>
    <td><%= promotion.service_id %></td>
    <td><%= promotion.product_id %></td>
    <td><%= link_to 'Show', promotion %></td>
    <td><%= link_to 'Edit', edit_promotion_path(promotion) %></td>
    <td><%= link_to 'Destroy', promotion, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Promotion', new_promotion_path %>

app/views/promotions/new.html.erb
<h1>New promotion</h1>

<%= render 'form' %>

<%= link_to 'Back', promotions_path %>

app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @promotion.name %>
</p>

<p>
  <b>Discout:</b>
  <%= @promotion.discout %>
</p>

<p>
  <b>Service:</b>
  <%= @promotion.service_id %>
</p>

<p>
  <b>Product:</b>
  <%= @promotion.product_id %>
</p>


<%= link_to 'Edit', edit_promotion_path(@promotion) %> |
<%= link_to 'Back', promotions_path %>

app/views/references/_form.html.erb
<%= form_for(@reference) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<h1>Listing references</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @references.each do |reference| %>
  <tr>
    <td><%= reference.name %></td>
    <td><%= reference.description %></td>
    <td><%= link_to 'Show', reference %></td>
    <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
    <td><%= link_to 'Destroy', reference, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<h1>New reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reference.name %>
</p>

<p>
  <b>Description:</b>
  <%= @reference.description %>
</p>


<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :technology %><br />
    <%= f.text_area :technology %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price_pack %><br />
    <%= f.text_field :price_pack %>
  </div>
  <div class="field">
    <%= f.label :price_time %><br />
    <%= f.text_field :price_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Listing services</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Technology</th>
    <th>Quantity</th>
    <th>Price pack</th>
    <th>Price time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @services.each do |service| %>
  <tr>
    <td><%= service.name %></td>
    <td><%= service.description %></td>
    <td><%= service.technology %></td>
    <td><%= service.quantity %></td>
    <td><%= service.price_pack %></td>
    <td><%= service.price_time %></td>
    <td><%= link_to 'Show', service %></td>
    <td><%= link_to 'Edit', edit_service_path(service) %></td>
    <td><%= link_to 'Destroy', service, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @service.name %>
</p>

<p>
  <b>Description:</b>
  <%= @service.description %>
</p>

<p>
  <b>Technology:</b>
  <%= @service.technology %>
</p>

<p>
  <b>Quantity:</b>
  <%= @service.quantity %>
</p>

<p>
  <b>Price pack:</b>
  <%= @service.price_pack %>
</p>

<p>
  <b>Price time:</b>
  <%= @service.price_time %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>